apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumetaskapihpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumetaskapihpa
  template:
    metadata:
      labels:
        app: consumetaskapihpa
    spec:
      containers:
      - name: consumetaskapihpa
        image: ravikkat/task2consumeapi
        resources:
          limits:
            memory: "256Mi"
            cpu: "800m"
---
apiVersion: v1
kind: Service
metadata:
  name: consumetaskapihpaservice
spec:
  type: NodePort
  selector:
    app: consumetaskapihpa
  ports:
  - port: 80
    targetPort: 80
    nodePort: 31846
